#ifndef SETTINGS
#define SETTINGS

#define MOVE_MAGNITUDE_FLOOR 1.0
#define MOVE_MAGNITUDE_CEILING 5.0
#define ANGLE_MAGNITUDE_FLOOR -5.0
#define ANGLE_MAGNITUDE_CEILING 5.0
#define DNA_LENGTH 100

#endif